name: flutter_paint
description: Paint

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  event_bus: ^1.1.0
  flutter_colorpicker: ^0.2.5
  path_provider: ^1.2.0
  toast: ^0.1.5
  image_picker: ^0.6.0
  share: ^0.6.2
  image_gallery_saver: ^1.1.0
  permission_handler: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
